export const FETCHING_POKELIST = 'FETCHING_POKELIST';
export const FETCHING_POKELIST_SUCCESS = 'FETCHING_POKELIST_SUCCESS';
export const FETCHING_POKELIST_FALIURE = 'FETCHING_POKELIST_FALIURE';

export const FETCHING_POKMON = 'FETCHING_POKMON';
export const FETCHING_POKMON_SUCCESS = 'FETCHING_POKMON_SUCCESS';
export const FETCHING_POKMON_FALIURE = 'FETCHING_POKMON_FALIURE';